Disable system opencl and use from submodules. Update dependencies.
Upstream currently does not support the latest opencl-clhpp
2024.10.24 that just reached the official repositories, giving
the following build error:

```
In file included from /build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp:14,
                 from /build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_wrapper.hpp:73,
                 from /build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_common.hpp:6,
                 from /build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_event.hpp:7,
                 from /build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_event.cpp:5:
/build/openvino/src/openvino/src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp:50:1: error: redefinition of ‘struct cl::detail::param_traits<cl::detail::cl_device_info, 16648>’
   50 | CL_HPP_DECLARE_PARAM_TRAITS_(cl_device_info, CL_DEVICE_SUB_GROUP_SIZES_INTEL, vector<size_type>)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/CL/opencl.hpp:1909:1: note: previous definition of ‘struct cl::detail::param_traits<cl::detail::cl_device_info, 16648>’
 1909 | CL_HPP_DECLARE_PARAM_TRAITS_(cl_device_info, CL_DEVICE_SUB_GROUP_SIZES_INTEL, cl::vector<size_type>)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Disable usage of system opencl and use opencl from git submodules.