aur: konform-browser 140.12.0.102-2
use vendored libevent due to build error with distribution libevent 2.1.13:
	In file included from Unified_cpp_ipc_chromium0.cpp:83:
	/home/user/pkg/konform-browser/src/src/source-140.12.0/ipc/chromium/src/base/message_pump_libevent.cc:44:1: error: use of undeclared identifier 'EVENT__SIZEOF_TIME_T'

fix building with _build_profiled=true