depends: change zimg to zimg-git due to compile error
The following compile error occurs if using zimg release version (currently at 2.3):
libavfilter/vf_zscale.c:387:16: error: ‘ZIMG_TRANSFER_IEC_61966_2_1’ undeclared (first use in this function)

FFmpeg seems to be using code from zimg git version since using zimg-zit fix this error.
This was introduced in the following upstream git commit:
http://git.videolan.org/?p=ffmpeg.git;a=commit;h=b96a6e2024fa2b52d6a2473a7cf16ee20a8ab5c8

When zimg releases a new version we can consider to change back this dependency.