systemd-selinux: fix build with gnu-efi 3.0.13-1
gnu-efi 3.0.13 broken systemd build (cf.
https://github.com/fishilico/arch-selinux/runs/2105907768).

    cc -c ../systemd-stable/src/boot/efi/console.c -o src/boot/efi/console.c.o
    -Wall -Wextra -std=gnu90 -nostdinc -fpic -fshort-wchar -ffreestanding
    -fno-strict-aliasing -fno-stack-protector -Wsign-compare
    -Wno-missing-field-initializers -isystem /usr/include/efi -isystem
    /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include
    version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER
    -DGNU_EFI_USE_MS_ABI -O2
    ../systemd-stable/src/boot/efi/console.c:12: warning:
    "EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL_GUID" redefined
       12 | #define EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL_GUID \
          |
    In file included from /usr/include/efi/efi.h:63,
                     from ../systemd-stable/src/boot/efi/console.c:3:
    /usr/include/efi/eficonex.h:22: note: this is the location of the
    previous definition
       22 | #define EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL_GUID \
          |
    ../systemd-stable/src/boot/efi/console.c:27:3: error: conflicting
    types for ‘EFI_KEY_STATE’
       27 | } EFI_KEY_STATE;
          |   ^~~~~~~~~~~~~
    In file included from /usr/include/efi/efi.h:63,
                     from ../systemd-stable/src/boot/efi/console.c:3:
    /usr/include/efi/eficonex.h:32:3: note: previous declaration of
    ‘EFI_KEY_STATE’ was here
       32 | } EFI_KEY_STATE;
          |   ^~~~~~~~~~~~~

This was reported and fixed in systemd in
https://github.com/systemd/systemd/pull/18987, but not backported in
systemd-stable.

Create a patch in order to build system on systems with gnu-efi 3.0.13.
Do not bump pkgrel as the runtime dependencies did not change.