PKGBUILD: Fix missing go-turbo
This commit fixes the following error:

  ERROR Unable to find Go binary. Please report this issue at https://gith
  ub.com/vercel/turbo/issues and include your package manager and version
  along with the following information:
          os=linux
          arch=x86_64
          turbo-version=1.10.3
          turbo-bin=/usr/bin/turbo
          go-turbo-bin=/usr/bin/go-turbo

  Error: Failed to execute turbo (Unable to locate Go binary).

Signed-off-by: Shohei Maruyama <cheat.sc.linux@outlook.com>