upgpkg: 2026.04.27.r112.g09d1c65-2: switch back to extern vulkan_headers, please read commit body
I am switching to the extern vulkan_headers because it currently fails
to build normally using system headers:
/build/citron-neo-git/src/emulator/externals/Vulkan-Utility-Libraries/include/vulkan/vk_enum_string_helper.h:8459:24: error: use of undeclared identifier 'VK_PIPELINE_CREATE_2_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NV'; did you mean 'VK_PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT'?
 8459 |     if (input_value == VK_PIPELINE_CREATE_2_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NV) return "VK_PIPELINE_CREATE_2_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NV";
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        VK_PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT
/usr/include/vulkan/vulkan_core.h:8307:40: note: 'VK_PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT' declared here
 8307 | static const VkPipelineCreateFlagBits2 VK_PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT = 0x01000000ULL;