Revert "Bump to 4.20.8_1-1"
This reverts commit a105770c76164bcfd95f0df96741e714f14f8597.

Currently fails to build with MuQSS because of:

Kernel: arch/x86/boot/bzImage is ready  (#1)
ERROR: "sched_smt_present" [arch/x86/kvm/kvm-intel.ko] undefined!

Don't have time today to research it, will check it out later and merge
any necessary patches to fix.