Add the suggested conflict by @dreieck:  dreieck commented on 2023-07-28 10:38 (UTC)
Please add conflicts=('tumbler-extra-thumbnailers'):

error: failed to commit transaction (conflicting files)
gnome-dds-thumbnailer: /usr/share/thumbnailers/dds.thumbnailer exists in filesystem (owned by tumbler-extra-thumbnailers)
Errors occurred, no packages were upgraded.