Add libxt to depends
This is required for rclock at least:

> rclock.C:39:10: fatal error: X11/Intrinsic.h: No such file or directory
>    39 | #include <X11/Intrinsic.h>      /* Xlib, Xutil, Xresource, Xfuncproto */
>       |          ^~~~~~~~~~~~~~~~~