Fix index generation command
Set `PYTHONPATH` to the aws-cli project root dir, so the gen-ac-index
script can find the modules it needs.

```
Traceback (most recent call last):
  File "./scripts/gen-ac-index", line 8, in <module>
    from awscli.autocomplete.local import indexer
ModuleNotFoundError: No module named 'awscli'
```

Also moved the gen-ac-index script part to the build() function, and
add a install command to move the built index into place in the
package() function.