python-vl-convert: add protobuf to makedepends
else this happens:
error: failed to run custom build command for `denokv_proto v0.2.1`

Caused by:
  process didn't exit successfully: `/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.2.0/target/release/build/denokv_proto-747931d42d1c539c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./schema/datapath.proto

  --- stderr
  thread 'main' panicked at /home/omnius/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10:
  Could not find `protoc` installation and this build crate cannot proceed without (...)