openvas-scanner: update to 23.18.0
which fails to compile:

  t-printf.c: In function ‘check_fprintf_sf’:
  t-printf.c:452:18: error: expected identifier or ‘(’ before ‘nullptr’
    452 |   volatile char *nullptr = NULL; /* Avoid compiler warning.  */
        |                  ^~~~~~~