Initial commit of 3.1.0-beta.1
Version 3.1.0-beta.1 looks to be the first released version that's open
source.

Installing from source. Initally tried using the system electron6. Ran
into issues with it, with a slight mismatch between node 12 and electron
6. Error message:

```
App threw an error during load
Error: The module '/tmp/.org.chromium.Chromium.BfwVJN'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```