update commit and fix hardening-wrapper problem
hardening-wrapper add -fstack-check starting with version 10.
This leads to
error: 'asm' operand has impossible constraints
during the compilation because we effectively don't have enough
registers.

Wir circumvent the problem by disabling PIC (and PIE) when
hardening-wrapper is installed (since these options also need a
register).

The commit hash is the same now as for the package in [extra].