Fix libr_util.so linking issue
libr_util.so fails to link with PIE, so we explicitly remove it from
CFLAGS.
```
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

This also includes the fix for CVE-2021-32613.