Fix bugs introduced with v. 3.3
Nominally:
- `Missing custom libsqlite3, run "make deps" to setup.`
- `shared/idmap/shift_linux.go:29:10: fatal error: attr/xattr.h: No such file or directory`