Fix compilation error related to markdown module
Users were previously getting errors like the following when attempting
to build the package:

> V self compiling (-prod)...
> builder error: cannot import module "markdown" (not found)
> ==> ERROR: A failure occurred in build().
>     Aborting...
> error making: %!s(func() string=0x55b93b10ba60)

Although not obvious at first glance, this occured while building
`vdoc`, as it requires the markdown module to be installed in the
building user's home directory. This commit satisfies said requirement.