require Java 8
It still worked with OpenJDK 11, but not with OpenJDK 13:

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/net/ssl/TrustManager