upgpkg: fanficfare-git 3.27.0.r10.g19af3ea7-1
Now with cloudflare "anti-bot" circumvention because cloudflare is terrible
and fanfiction.net decided to be terrible too.

May not actually work, since my testing "successfully" reported:
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

But apparently it sometimes does work. Who knows. Cloudflare is arbitrary and nuts.