Include server.js in the package.
s of today, when launching stremio, we have this error :

> $ stremio
> thread 'main' (24315) panicked at src/server.rs:19:51:
> Failed to read SERVER_PATH env: NotPresent
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is due to the following code at server.rs in the source :

```
impl Server {
    pub fn new() -> Self {
        let server_path = env::var("SERVER_PATH").expect("Failed to read SERVER_PATH env");
        let file = PathBuf::from(&server_path);

        Self {
            process: None,
            file,
        }
    }
```

Where it need to get the SERVER_PATH env pointing to a `server.js` file.
This `server.js` file is in the sources of stremio :
https://github.com/Stremio/stremio-linux-shell/blob/main/data/server.js

We know install the server.js onto /usr/lib/stremio/server.js

And patch rust source code to use this path as default value for
env.SERVER_PATH.

That way, stremio binary is working out of the box without having to
download the server.js manually and specify the env variable.