Explicitly build against OpenSSL 1.1
Otherwise we end up building against the OpenSSL 3 headers even though this version of cryptography doesn't support OpenSSL 3.

Fixes errors such as:
ImportError: /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: ERR_new