Bump version to 0.11.6, get sources via git instead tarball
Downloading sources via git instead of GitHub's tarball to fix the
following error:
```
LookupError: setuptools-scm was unable to detect version for 'python-setuptools-rust/src/setuptools-rust-0.11.6'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```