update and patch out -Werror
Thanks for making this very readable warning an error on gcc 12.1, google

FAILED: external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o
/usr/bin/c++ -DEIGEN_MPL2_ONLY -DENABLE_CPU_FP16_TRAINING_OPS -DFLATBUFFERS_LOCALE_INDEPENDENT=1 -DORT_NO_RTTI -DPLATFORM_POSIX -I/home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/include -I/home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/grpc -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -std=c++0x -Wall -pedantic -Werror -Wextra -Werror=shadow -faligned-new -Werror=implicit-fallthrough=2 -Wunused-result -Werror=unused-result -Wunused-parameter -Werror=unused-parameter -fsigned-char -O3 -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -fPIE -fno-rtti -Wold-style-cast -std=gnu++17 -MD -MT external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o -MF external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o.d -o external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o -c /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp
In file included from /usr/include/c++/12.1.0/ios:40,
                 from /usr/include/c++/12.1.0/istream:38,
                 from /usr/include/c++/12.1.0/sstream:38,
                 from /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/include/flatbuffers/code_generators.h:21,
                 from /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp:20:
In static member function 'static std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)',
    inlined from 'static void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:423:21,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.tcc:532:22,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:2171:19,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:2196:22,
    inlined from 'static std::string flatbuffers::dart::DartGenerator::ImportAliasName(const std::string&)' at /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp:113:18,
    inlined from 'static const std::string flatbuffers::dart::DartGenerator::MaybeWrapNamespace(const std::string&, flatbuffers::Namespace*, const flatbuffers::FieldDef&)' at /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp:408:29:
/usr/include/c++/12.1.0/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In static member function 'static std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)',
    inlined from 'static void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:423:21,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.tcc:532:22,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:2171:19,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/include/c++/12.1.0/bits/basic_string.h:2196:22,
    inlined from 'static std::string flatbuffers::dart::DartGenerator::ImportAliasName(const std::string&)' at /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp:113:18,
    inlined from 'virtual bool flatbuffers::dart::DartGenerator::generate()' at /home/haagch-collabora/4tb/onnxruntime-git/src/onnxruntime/cmake/external/flatbuffers/src/idl_gen_dart.cpp:88:40:
/usr/include/c++/12.1.0/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors