Switch from swig to swig3
Building with the current swig 4.1.1 causes armory to fail launching with the error
"ImportError: cannot import name ConfigFile_fleshOutArgs".

Go back to swig 3, which works fine.

While at it, make swig a makedependency. It was never needed at runtime.