upgpkg: freedv-gui 2.3.0-3 fix _Vector_impl_data::_M_finish’ is used uninitialized
fix the error

    inlined from ‘SerialPortInRigController::SerialPortInRigController(std::string, bool)’ at /home/rainbow/sources/archlinux/aur/freedv-gui/src/freedv-gui-2.3.0/src/rig_control/SerialPortInRigController.cpp:47::
/usr/include/c++/16.1.1/bits/stl_vector.h:1408:27: error: ‘((std::vector<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >*)<unknown>)[2].std::vector<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_M_impl.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl::std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl_data.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl_data::_M_finish’ is used uninitialized [-Werror=uninitialized]
 1408 |         if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)
      |             ~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/c++/16.1.1/bits/stl_vector.h:1408:54: error: ‘((std::vector<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >*)<unknown>)[2].std::vector<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_M_impl.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl::std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl_data.std::_Vector_base<std::function<void(IRigController*)>, std::allocator<std::function<void(IRigController*)> > >::_Vector_impl_data::_M_end_of_storage’ is used uninitialized [-Werror=uninitialized]
 1408 |         if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)

present in gcc 16.1.

see https://github.com/drowe67/freedv-gui/issues/1342