use older insight-0.8.4 version
The newer version of insight (0.10.1) breaks inboxer.
It fails to start with the following error:
   Error: Cannot find module 'tmp'