upgpkg: ms-tpm-20-ref-git r167.51d7b24-1: disable SM3 and SM4
Building with these algorithms enabled (as done by upstream commit
9dba28162d7d75403a77ef7f20ad513e8b07a7df) leads to linking errors:

/usr/bin/ld: CryptSym.c:(.text+0xbef): undefined reference to `SM4_encrypt'
/usr/bin/ld: CryptSym.c:(.text+0xc6d): undefined reference to `SM4_set_key'
/usr/bin/ld: CryptSym.c:(.text+0xc87): undefined reference to `SM4_decrypt'
/usr/bin/ld: tpm/src/libtpm.a(libtpm_a-CryptHash.o):(.data.rel.ro+0x0): undefined reference to `sm3_init'
/usr/bin/ld: tpm/src/libtpm.a(libtpm_a-CryptHash.o):(.data.rel.ro+0x8): undefined reference to `sm3_update'
/usr/bin/ld: tpm/src/libtpm.a(libtpm_a-CryptHash.o):(.data.rel.ro+0x10): undefined reference to `sm3_final'

According to upstream commit e85c224b7719df1c54cfd8c0a054504ee4c666c3, these
functions might only be included in the unreleased OpenSSL 1.2.