don't accidentally delete tmp package
This line would delete folder 'node_modules/tmp' which
contains package 'tmp'.
Because of this, inboxer-1.1.5 would fail to start with:
  Error: Cannot find module 'tmp'

I didn't find any other 'tmp' folders in 'node_modules' worth deleting.
Thus, this line was not needed at all in the first place.