Fix svt-av1 build
Some function declarations were moved to packet_internal.h[1].

This fixes the following build error:

libavcodec/libsvt_av1.c: In function ‘eb_receive_packet’:
libavcodec/libsvt_av1.c:396:5: error: implicit declaration of function ‘ff_side_data_set_encoder_stats’ [-Werror=implicit-function-declaration]
  396 |     ff_side_data_set_encoder_stats(pkt, headerPtr->qp * FF_QP2LAMBDA, NULL, 0, pict_type);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

References
----------
https://github.com/FFmpeg/FFmpeg/commit/6e1903938befc0bce2f64e01770af2f65d625cfc